
// get address api
export const GET_CITY = 'GET_CITY';
export const GET_DISTRICT = 'GET_DISTRICT';
export const GET_COMMUTE = 'GET_COMMUTE';
export const GET_CITY_REQUESTED = 'GET_CITY_REQUESTED';
export const GET_DISTRICT_REQUESTED = 'GET_DISTRICT_REQUESTED';
export const GET_COMMUTE_REQUESTED = 'GET_COMMUTE_REQUESTED';

//user register
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_REQUESTED = 'USER_REGISTER_REQUESTED';

//user payment
export const USER_PAYMENT_REQUESTED = 'USER_PAYMENT_REQUESTED'
export const USER_PAYMENT = 'USER_PAYMENT'

export const USER_EXECUTE_PAYMENT_REQUESTED = 'USER_EXECUTE_PAYMENT_REQUESTED'
export const USER_EXECUTE_PAYMENT = 'USER_EXECUTE_PAYMENT'

// search post
export const POSTS_SEARCH_LOADING = 'POSTS_SEARCH_LOADING'
export const POSTS_SEARCH_COMPLETE = 'POSTS_SEARCH_COMPLETE'

//create post
export const POSTS_CREATE_POST_REQUEST = 'POSTS_CREATE_POST_REQUEST'
export const POSTS_CREATE_POST_RESPONSE = 'POSTS_CREATE_POST_RESPONSE'

//category
export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_CATEGORIES_REQUEST'
export const GET_ALL_CATEGORIES_COMPLETE = 'GET_ALL_CATEGORIES_COMPLETE'

//upload file
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST'
export const UPLOAD_FILE_COMPLETE = 'UPLOAD_FILE_COMPLETE'