
// get address api
export const GET_CITY = 'GET_CITY';
export const GET_DISTRICT = 'GET_DISTRICT';
export const GET_COMMUTE = 'GET_COMMUTE';
export const GET_CITY_REQUESTED = 'GET_CITY_REQUESTED';
export const GET_DISTRICT_REQUESTED = 'GET_DISTRICT_REQUESTED';
export const GET_COMMUTE_REQUESTED = 'GET_COMMUTE_REQUESTED';

//user register
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_REQUESTED = 'USER_REGISTER_REQUESTED';

//user payment
export const USER_PAYMENT_REQUESTED = 'USER_PAYMENT_REQUESTED'
export const USER_PAYMENT = 'USER_PAYMENT'

export const USER_EXECUTE_PAYMENT_REQUESTED = 'USER_EXECUTE_PAYMENT_REQUESTED'
export const USER_EXECUTE_PAYMENT = 'USER_EXECUTE_PAYMENT'