export const LOGIN_USER = 'LOGIN_USER'
export const USER_LOGGEDIN = 'USER_LOGGEDIN'

export const LOGOUT_USER = 'LOGOUT_USER'
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT'

export const CHECK_JWT_EXP = 'CHECK_JWT_EXP'
